export type Service={name:string;price:string;duration:string;description?:string;note?:string;image?:string}; export type Category={name:string;short:string;services:Service[];image?:string};
const make=(list:string[][])=>list.map(([name,price,duration,description,note])=>({name,price,duration,description,note}));
export const categories:Category[]=[
 {name:'Massage',short:'Unwind, restore and reset.',services:make([['Aromatherapy full body massage','£50','1 hour'],['Aromatherapy back massage','£40','30 minutes'],['Deep tissue full body massage','£50','1 hour'],['Deep tissue back massage','£40','30 minutes'],['90 minute deluxe full body massage','£70','1 hour 30 minutes'],['Back scrub & hot oil massage','£42','40 minutes'],['Scalp massage','£20','20 minutes'],['Hand & arm massage','£30','25 minutes'],['Reiki','£50','1 hour']])},
 {name:'Facials & advanced skin',short:'Thoughtful treatments for your skin.',services:make([['Lymphflo Facial','£65','1 hour','Sculpting and detox facial.'],['The Million Dollar Facial','£110','1 hour','Microneedling and dermaplaning facial.'],['Mini Million Dollar Facial','£45','45 minutes'],['Oxy Pro','£60','45 minutes','Facial yoga facial with oxygenated and cryo masks.'],['Superfacial – Hydrate','£55','45 minutes'],['Superfacial – Glow','£55','45 minutes'],['Dermaplaning facial','£57','1 hour'],['Dermaplaning with Miracle Mask','£70','1 hour'],['Microneedling','£80','55 minutes'],['Body microneedling','£75','35 minutes'],['Hair rejuvenation course of 6','£380','25 minutes each'],['Bacial','£55','45 minutes'],['Radiate peel','£60','30 minutes'],['Rejuvenate peel','£60','30 minutes'],['Eliminate peel','£60','30 minutes'],['Dermaplaning add-on','£10','15 minutes']])},
 {name:'Lycon waxing',short:'Professional waxing in a calm, private setting.',services:make([['Full leg wax','£40','1 hour 10 minutes'],['3/4 leg wax','£35','45 minutes'],['Half leg wax','£25','30 minutes'],['Forearm wax','£18','30 minutes'],['Underarm wax','£15','15 minutes'],['Bikini line wax','£18','15 minutes'],['Extended bikini line','£29','30 minutes'],['Intimate wax','£40','45 minutes'],["Men's back/chest wax",'£37','45 minutes'],['Eyebrow wax','£13.50','15 minutes'],['Lip wax','£10','15 minutes'],['Chin wax','£14','15 minutes'],['Lip & chin wax','£20','1 hour'],['Nostril wax','£10','15 minutes']])},
 {name:'Eyes & lashes',short:'The finishing touches.',services:make([['Nouveau LVL lash lift','£50','1 hour','','Patch test required for new clients.'],['Eyebrow wax & tint','£24.50','30 minutes'],['Eyebrow wax','£13.50','15 minutes'],['Eyebrow tint','£12','15 minutes'],['Eyelash tint','£15','20 minutes']])},
 {name:'Cryotherapy',short:'Consultation-led treatment options.',services:make([['Cryotherapy consultation & skin-tag removal','from £70','15 minutes'],['Milia removal','from £60','15 minutes'],['Cherry angioma removal','from £60','15 minutes'],['Pigmentation treatment','from £70','15 minutes'],['Warts/verrucae removal','from £150','20 minutes']])},
 {name:'Holistic treatments',short:'A little extra time to switch off.',services:make([['Indian head massage','£40','45 minutes'],['Hopi ear candle treatment','£30','35 minutes'],['Hopi ear candle treatment with scalp massage','£45','1 hour']])}];
export const slots=[{id:'one',location:'Horncastle',time:'Example Tuesday · 10:00 am',length:'90 minutes'},{id:'two',location:'Horncastle',time:'Example Thursday · 1:30 pm',length:'60 minutes'},{id:'three',location:'Woodhall Spa',time:'Example Wednesday · 11:00 am',length:'75 minutes'}];
export const services=categories.flatMap(category=>category.services);
