'use client';
import {useEffect,useState} from 'react';
import {defaultSiteContent,type SiteContent} from '@/lib/site-content';
import type {Category,Service} from '@/lib/sandbox-data';

const blankService:Service={name:'New treatment',price:'£0',duration:'30 minutes',description:'',note:''};
export default function ContentEditor(){
 const [content,setContent]=useState<SiteContent>(defaultSiteContent);const [status,setStatus]=useState('');const [section,setSection]=useState<'overview'|'content'|'services'|'locations'>('overview');
 useEffect(()=>{fetch('/api/content').then(r=>r.json()).then(setContent)},[]);
 const field=(key:keyof SiteContent,value:string)=>setContent({...content,[key]:value});
 const updateCategory=(ci:number,patch:Partial<Category>)=>setContent({...content,categories:content.categories.map((c,i)=>i===ci?{...c,...patch}:c)});
 const updateService=(ci:number,si:number,patch:Partial<Service>)=>updateCategory(ci,{services:content.categories[ci].services.map((s,i)=>i===si?{...s,...patch}:s)});
 const addCategory=()=>setContent({...content,categories:[...content.categories,{name:'New category',short:'Add a short introduction.',services:[]}]});
 const removeCategory=(ci:number)=>confirm('Remove this category and all its treatments?')&&setContent({...content,categories:content.categories.filter((_,i)=>i!==ci)});
 const addService=(ci:number)=>updateCategory(ci,{services:[...content.categories[ci].services,{...blankService,name:`New treatment ${content.categories[ci].services.length+1}`}]});
 const removeService=(ci:number,si:number)=>confirm('Remove this treatment?')&&updateCategory(ci,{services:content.categories[ci].services.filter((_,i)=>i!==si)});
 const save=async()=>{setStatus('Saving…');const r=await fetch('/api/content',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(content)});setStatus(r.ok?'Changes published':'Could not save — please sign in again')};
 return <main className="admin-shell"><aside className="admin-sidebar"><a className="admin-brand" href="/">SOUL LIFTING<br/><i>THERAPIES</i></a><nav>{(['overview','content','services','locations'] as const).map(x=><button className={section===x?'active':''} onClick={()=>setSection(x)} key={x}>{x==='overview'?'Dashboard':x==='content'?'Homepage':x==='services'?'Treatments':'Business details'}</button>)}</nav><a href="/services">View customer app ↗</a></aside><section className="admin-workspace"><header><div><p className="eyebrow">Emma’s admin</p><h1>{section==='overview'?'Dashboard':section==='content'?'Edit homepage':section==='services'?'Treatment catalogue':'Business details'}</h1></div><div className="admin-save"><span>{status}</span><button onClick={save}>Save & publish</button></div></header>
 {section==='overview'&&<div className="admin-overview"><div className="admin-stat"><span>Published treatments</span><strong>{content.categories.reduce((n,c)=>n+c.services.length,0)}</strong></div><div className="admin-stat"><span>Categories</span><strong>{content.categories.length}</strong></div><div className="admin-stat"><span>Locations</span><strong>2</strong></div><article className="admin-card wide"><h2>What you can update here</h2><p>Change homepage wording, contact details, location information, categories, treatments, prices, durations, descriptions and important notes. Press <b>Save & publish</b> when you are ready for customers to see the changes.</p></article></div>}
 {section==='content'&&<div className="admin-card admin-fields"><label>Business name<input value={content.businessName} onChange={e=>field('businessName',e.target.value)}/></label><label>Business descriptor<input value={content.descriptor} onChange={e=>field('descriptor',e.target.value)}/></label><label>Main headline<input value={content.heroTitle} onChange={e=>field('heroTitle',e.target.value)}/></label><label>Gold headline wording<input value={content.heroAccent} onChange={e=>field('heroAccent',e.target.value)}/></label><label className="wide">Homepage introduction<textarea rows={3} value={content.heroIntro} onChange={e=>field('heroIntro',e.target.value)}/></label><label className="wide">Announcement banner (leave blank to hide)<input value={content.notice} onChange={e=>field('notice',e.target.value)} placeholder="Example: Gift vouchers now available"/></label></div>}
 {section==='locations'&&<div className="admin-card admin-fields"><label>Phone<input value={content.phone} onChange={e=>field('phone',e.target.value)}/></label><label>Email<input value={content.email} onChange={e=>field('email',e.target.value)}/></label><label className="wide">Horncastle address<textarea rows={3} value={content.horncastle} onChange={e=>field('horncastle',e.target.value)}/></label><label className="wide">Woodhall Spa address<textarea rows={3} value={content.woodhall} onChange={e=>field('woodhall',e.target.value)}/></label></div>}
 {section==='services'&&<div className="service-manager"><button className="add-category" onClick={addCategory}>＋ Add category</button>{content.categories.map((cat,ci)=><article className="admin-card category-editor" key={ci}><div className="category-editor-head"><div><input className="category-name" value={cat.name} onChange={e=>updateCategory(ci,{name:e.target.value})}/><input className="category-intro-input" value={cat.short} onChange={e=>updateCategory(ci,{short:e.target.value})}/></div><button className="danger" onClick={()=>removeCategory(ci)}>Remove category</button></div><div className="treatment-editor-list">{cat.services.map((s,si)=><div className="treatment-editor" key={si}><div className="treatment-editor-title"><input value={s.name} onChange={e=>updateService(ci,si,{name:e.target.value})}/><button className="danger" onClick={()=>removeService(ci,si)}>Remove</button></div><div className="treatment-editor-meta"><label>Price<input value={s.price} onChange={e=>updateService(ci,si,{price:e.target.value})}/></label><label>Duration<input value={s.duration} onChange={e=>updateService(ci,si,{duration:e.target.value})}/></label></div><label>Description<textarea rows={2} value={s.description??''} onChange={e=>updateService(ci,si,{description:e.target.value})}/></label><label>Important note<textarea rows={2} value={s.note??''} onChange={e=>updateService(ci,si,{note:e.target.value})}/></label></div>)}</div><button className="add-treatment" onClick={()=>addService(ci)}>＋ Add treatment to {cat.name}</button></article>)}</div>}
 </section></main>
}
